remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: Teaching Critical AI Literacy
description: Resources from Anastasia Salter's "Teaching Critical AI Literacy" talk, March 2025
